-- NOTE: This file is intentionally disabled.
-- The Stalker 2 UEVR profile uses the IK rig (libs/ik.lua) which manages arms via
-- a PoseableMesh clone of pawn.Mesh. Having this script also call hands.createFromConfig()
-- would create a second set of controller-attached hand meshes that conflict with the IK rig.
--
-- The libs/hands.lua auto-creation is also disabled in Entry.lua via hands.setAutoCreateHands(false).
--
-- DO NOT RE-ENABLE without removing IK, or you will get duplicate hands at your controllers.

-- local uevrUtils = require('libs/uevr_utils')
-- local hands = require('libs/hands')
-- local controllers = require('libs/controllers')
-- 
-- function on_level_change(level)
--     controllers.createController(0)
--     controllers.createController(1)
--     hands.reset()
--     local paramsFile = 'hands_parameters'
--     local configName = 'Main'
--     local animationName = 'Shared'
--     hands.createFromConfig(paramsFile, configName, animationName)
-- end
-- 
-- function on_xinput_get_state(retval, user_index, state)
--     if hands.exists() then
--         local isHoldingWeapon = false
--         local hand = Handed.Right
--         hands.handleInput(state, isHoldingWeapon, hand)
--     end
-- end
